# Generated by Django 4.1 on 2023-01-12 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BudgetCoreApp', '0004_expense_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moneys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.CharField(max_length=50)),
                ('expenses', models.CharField(max_length=50)),
                ('balance', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Money',
        ),
    ]
