# Generated by Django 4.1 on 2023-01-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetCoreApp', '0005_moneys_delete_money'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monies',
            fields=[
                ('user', models.BigAutoField(primary_key=True, serialize=False)),
                ('income', models.CharField(max_length=50)),
                ('expenses', models.CharField(max_length=50)),
                ('balance', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Moneys',
        ),
    ]
