# Generated by Django 4.1 on 2023-01-12 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetCoreApp', '0006_monies_delete_moneys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monies',
            name='expenses',
        ),
    ]
