# Generated by Django 4.1 on 2023-01-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetCoreApp', '0007_remove_monies_expenses'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyBudget',
            fields=[
                ('user', models.BigAutoField(primary_key=True, serialize=False)),
                ('expenses_type', models.CharField(max_length=50)),
                ('balance', models.CharField(max_length=50)),
                ('spend_money', models.CharField(max_length=20)),
                ('Expense_Income', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Monies',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='expense_type',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='name',
        ),
    ]
