# Generated by Django 4.1 on 2023-01-13 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetCoreApp', '0009_remove_moneybudget_balance_moneybudget_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0, max_length=24)),
                ('Balance_Left', models.CharField(default=0, max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BudgetCoreApp.moneybudget')),
            ],
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
