# Generated by Django 4.1 on 2023-01-13 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetCoreApp', '0010_expenses_delete_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneysBudget',
            fields=[
                ('user', models.BigAutoField(primary_key=True, serialize=False)),
                ('expenses_type', models.CharField(max_length=50)),
                ('spend_money', models.CharField(max_length=20)),
                ('date', models.CharField(default=0, max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='expenses',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BudgetCoreApp.moneysbudget'),
        ),
        migrations.DeleteModel(
            name='MoneyBudget',
        ),
    ]
