# Generated by Django 4.1 on 2023-01-14 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetCoreApp', '0011_moneysbudget_alter_expenses_user_delete_moneybudget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='Balance_Left',
            field=models.IntegerField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='amount',
            field=models.IntegerField(default=0, max_length=24),
        ),
        migrations.AlterField(
            model_name='moneysbudget',
            name='spend_money',
            field=models.IntegerField(max_length=20),
        ),
    ]
