# Generated by Django 4.1 on 2023-01-14 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetCoreApp', '0013_remove_expenses_balance_left'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenses',
            old_name='amount',
            new_name='total_income',
        ),
    ]
