# Generated by Django 4.1 on 2023-01-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetCoreApp', '0015_delete_expense_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='total_income',
            field=models.IntegerField(default=0),
        ),
    ]
